### ISSUE TITLE
HapiJS + RiotJS button onclick not working

### ISSUE THREAD

**Issue by rof20004** [dwyl/hapi-riot#15]
Hi, thanks for your examples codes.

I am with problem in one tag, here is my tag: (login.tag)

```
<html>
  <head>
    <title>Bem Vindo ao RiotJS</title>
  </head>
  <body>

      <label>{title}</label>
      <button onclick="{changeName}">Update Label</button>

    <script>
      this.title = 'Hellor World';

      changeName() {
        console.log('Is here!!');
      }
    </script>

  </body>
</html>

```

My button not call the changeName method, can you help me ?

Thanks and Regards,

Rodolfo Azevedo.

**Comment by jrans** [comment]
@rof20004 As you can see this repo is updating and we're working now and have a working solution so  will release it very soon. Will let you know when done but in the mean time if you have any suggestions let us know 😄

**Comment by rof20004** [comment]
@jrans Ok, thanks for answer, I will waiting then, I need to close this issue ?

**Comment by jackcarlisle** [comment]
@rof20004 you can close the issue when it's been updated and you're happy 👍

**Comment by rof20004** [comment]
@jackcarlisle Thanks guys, I am happy now =D, waiting for updates.

**Comment by jrans** [comment]
@rof20004 New version up! Let us know how you find it!

**Comment by rof20004** [comment]
@jrans Oh, nice to hear this 💃 , I will test and came back to post results, thanks for feedback.

**Comment by rof20004** [comment]
Hi @jrans I've tested right now and i get this error:

```
Debug: internal, implementation, error 
    SyntaxError: Unexpected token <: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/rof20004/hapijs-projects/hapi-riot/node_modules/hapi-riot/lib/index.js:24:7
    at Array.map (native)
    at loadTags (/home/rof20004/hapijs-projects/hapi-riot/node_modules/hapi-riot/lib/index.js:20:34)

```

This is my layout.html file:

```
<html>
  <head>
    <title>Hapi + Riot</title>
  </head>
  <body>
    <h1>Sistema Testes do Stack HapiJS + RiotJS</h1>
    <<<RIOT>>>
  </body>
</html>

```

Can you help ?

**Comment by rof20004** [comment]
@jrans I tried to debug myself, I teste removing layout.html from loadTags, because loadTags i think is only to return the files that have extension .tag, and it worked, my button click not worked, I need to import to my layout.html the bundle.js ?

**Comment by rof20004** [comment]
@jrans this is my index.tag:

```
<index>
  <label>{title}</label>
  <button onclick="{changeName}">Update Label</button>

  <script>
    this.title = 'Hellor World';

    this.on('mount', function() {
      console.log('Arquivo foi chamado');
    });

    changeName(e) {
      console.log('Is here!!');
    }
  </script>
</index>

```

The method 'mount' is executing when page loads but console.log show in my server console, not in browser.

**Comment by jrans** [comment]
@rof20004 
- Ok first problem makes sense. Essentially we are reading in all the files in the view directory and expect them to be tags hence if the layout.html is in the same folder on being required in will error. I will create an issue and either warn people not to do or make sure files have .tag extension if being required. So essentially you should follow the folder structure of those in example folder.
- If button click not working are you sure you've served up the compiled tags? You need to do that by yourself in whatever way you choose but essentially need to choose the tags fodler compile to one file and serve it up on some route. Again check how its done in either the basic or counter example.
- Finally the log appearing on your server console will be due to how riot renders a tag to html and therefore looks like it goes all the way to the mount in the lifecycle when finding the html so you should avoid any console.logs there unless you want them appearing in two places if at all! 

Check the [gotchas](https://github.com/dwyl/hapi-riot#lessons-learned--gotchas) for some of these issues.

I've copied your index.tag into one of the example projects and is working as expected so can only help if you direct me to your whole project.

**Comment by rof20004** [comment]
@jrans Thanks for answer. I will follow the examples in this git repository, I will try again.

Regards.

**Comment by rof20004** [comment]
@jrans hehehe, sorry, was my mistake, your team updated the hapi-riot plugin, BUT I FORGGETED TO UPDATE in MY PROJECT, I am so sorry T_T.. kkkkk

It is working now =D

**Comment by jrans** [comment]
@rof20004 Aha good news! Yes version 2.0 glad its working suggest any improvements as you use it!
